name: nlsst

channels:
  - conda-forge

dependencies:
  - python>=3.10,<3.13
  # User environment, not strictly needed for the kernel to run
  - jupyterlab
  # pip to install package that's only available in pip
  - pip

  - xarray
  - pygmt
  - scikit-image
  - gdal
  - pystac-client
  - pyproj
  - pandas
  - geopandas
  - intake
  - earthaccess
  - scikit-learn
  - ipywidgets
  - tqdm
  - boto3
  - rasterio
  - dask
  - rioxarray
  - cartopy
  - scipy
  - shapely
  - statsmodels
  - cycler
  - pytest
  - nbmake
  - matplotlib
  - ipympl
  - geoviews
  - hvplot

  # LibRadTran build dependencies
  - gsl
  - netcdf4
  - c-compiler
  - fortran-compiler
  - make
  - wget

  - pip:
    - pytensor
    - pymc